#!/bin/bash

# Simple bash script to take in a .tex LaTeX file, compile it, and convert it to .pdf

echo 'Retrieving File'

# Variables
FILEFULL=$1
FILE=${FILEFULL//.tex}
AUX=${FILE}".aux"
DVI=${FILE}".dvi"
LOG=${FILE}".log"

echo 'Compiling'

# Compile the file to a .dvi format
latex $FILEFULL

echo 'Converting to .pdf'

# Convert the file to a .pdf format
dvipdf $DVI

echo 'Removing Files'

# Remove unneccesary files
rm $DVI
rm $AUX
rm $LOG

echo 'Complete!'
